# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Home"
  url = "#demo"
  weight = 10

[[main]]
  name = "Artikel"
  url = "#posts"
  weight = 20

[[main]]
  name = "Portofolio"
  url = "#gallery"
  weight = 30


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
